# Generated by Django 3.2.3 on 2021-06-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210604_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='like'),
        ),
    ]
